# Generated by Django 6.0 on 2025-12-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('Farmhouse Suite', 'Farmhouse Suite'), ('Deluxe Room', 'Deluxe Room'), ('Luxury Suite', 'Luxury Suite')], max_length=50),
        ),
    ]
