# Generated by Django 6.0 on 2026-02-28 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homewelcomevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Your Name')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Your Email (optional)')),
                ('rating', models.IntegerField(help_text='Rate us from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('review_title', models.CharField(blank=True, max_length=200, verbose_name='Review Title')),
                ('review_text', models.TextField(verbose_name='Your Review')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured Review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='homewelcomevideo',
            name='video',
            field=models.FileField(upload_to='media/welcome.mp4'),
        ),
    ]
