# Generated by Django 6.0 on 2026-03-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_review_approved_at_remove_review_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment_score',
            field=models.FloatField(default=0.0, verbose_name='Sentiment Score'),
        ),
    ]
